#!/bin/bash

# Generate a compile_commands.json file

echo "
[
	{
		\"directory\":\"$PWD\",
		\"command\":\"clang++ -I$PWD -std=gnu++14\",
		\"file\":\"src/*.cpp\"
	},
	{
		\"directory\":\"$PWD\",
		\"command\":\"clang++ -I$PWD -std=gnu++14\",
		\"file\":\"tests/*cpp\"
	}
]
" > compile_commands.json
