LIBLUA=
INCLUA=

CXX=g++
AR=ar
CXXFLAGS=${LIBLUA} -I${INCLUA}

LIB_OUT=../libluacxx.a

LUACXX_STATE= \
	
LUACXX_TABLE=

default: ${LIB_OUT}

${LIB_OUT}:



define cxx
${CXX} $^ -o $^.o ${CXXFLAGS}
endef